// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func bodyStyles() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\n    body {\n      font-family: Arial, sans-serif;\n      margin: 20px;\n    }\n\n    input[type=\"text\"] {\n      width: 300px;\n      padding: 10px;\n      margin-right: 10px;\n      border: 1px solid #ccc;\n      border-radius: 5px;\n    }\n\n    button {\n      padding: 10px 20px;\n      border: none;\n      border-radius: 5px;\n      background-color: #007BFF;\n      color: white;\n      cursor: pointer;\n    }\n\n    button:hover {\n      background-color: #0056b3;\n    }\n\n    #search_results {\n      margin-top: 20px;\n      padding: 20px;\n      border: 1px solid #ddd;\n      border-radius: 5px;\n      background-color: #f9f9f9;\n    }\n\n    #search_results_container {\n      display: flex;\n      flex-wrap: wrap;\n    }\n\n    /* Transition for showing/hiding elements */\n    [x-cloak], [x-show=\"false\"] {\n      display: none !important;\n    }\n  </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
